import ElRowc from "element-ui/lib/row";
import ElColc from "element-ui/lib/col";
import ElFormItemc from "element-ui/lib/form-item";
import ElFormc from "element-ui/lib/form";
import ElSelectc from "element-ui/lib/select";
import ElInputc from "element-ui/lib/input";
import ElOptionc from "element-ui/lib/option";
import ElInputNumberc from "element-ui/lib/input-number";
import ElTablec from "element-ui/lib/table";
import ElTableColumnc from "element-ui/lib/table-column";
import ElCardc from "element-ui/lib/card";
import ElRadioGroupc from "element-ui/lib/radio-group";
import ElRadioButtonc from "element-ui/lib/radio-button";
import ElTagc from "element-ui/lib/tag";
import ElCheckboxGroupc from "element-ui/lib/checkbox-group";
import ElCheckboxc from "element-ui/lib/checkbox";
import ElCheckboxButtonc from "element-ui/lib/checkbox-button";
import ElTooltipc from "element-ui/lib/tooltip";
import ElTransferc from "element-ui/lib/transfer";

import "element-ui/lib/theme-chalk/index.css";

export var ElRow = ElRowc;
export var ElCol = ElColc;
export var ElFormItem = ElFormItemc;
export var ElForm = ElFormc;
export var ElSelect = ElSelectc;
export var ElInput = ElInputc;
export var ElOption = ElOptionc;
export var ElInputNumber = ElInputNumberc;
export var ElTable = ElTablec;
export var ElTableColumn = ElTableColumnc;
export var ElCard = ElCardc;
export var ElRadioGroup = ElRadioGroupc;
export var ElRadioButton = ElRadioButtonc;
export var ElTag = ElTagc;
export var ElCheckboxGroup = ElCheckboxGroupc;
export var ElCheckbox = ElCheckboxc;
export var ElCheckboxButton = ElCheckboxButtonc;
export var ElTooltip = ElTooltipc;
export var ElTransfer = ElTransferc;

import Vue from "vue";
Vue.prototype.$ELEMENT = { size: "mini", zIndex: 3000 };
